name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.8.0]

    steps:
      uses: actions/aws/cli@master
      with:
        secrets: [${{ AWS_ACCESS_KEY_ID }}, ${{ AWS_SECRET_ACCESS_KEY }}]
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run build
        # npm test
        npm run deploy
      env:
        CI: true
